### PR TITLE
Hapi9

### PR DESCRIPTION
**Pull request by serslon**
adapting to work with the API HAPI 9.0.1. Fixed tests on the new API as the same

### CODE REVIEW

**Comment by asafdav** [comment]
Hi, thank you for this pull request, it looks awesome. 
can you please squash your commits ? 

Thanks

**Comment by serslon** [comment]
Ready one commit.

**Comment by AdrieanKhisbe** [comment]
Seems to be good to be shipped :)

**Comment by asafdav** [comment]
@AdrieanKhisbe Thanks for the reminder, @serslon Thanks a lot !

**Comment by AdrieanKhisbe** [comment]
no problem :), you're welcome. and thanks @serslon too!

**Pull request merged**
